PoC.OpenIddict.Client/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace PoC.OpnIddict.Client.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PoC.OpenIddict.Client/Pages/Gwcallback.cshtml.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace PoC.OpnIddict.Client.Pages
{
    public class GwCallback : PageModel
    {
        public string? ResponseText { get; private set; }

        private string OpeniddictUrl = "https://localhost:7063";
        public string ClientUrl { get; set; } = "https://localhost:7216";

        public async Task<ActionResult> OnGetAsync()
        {
            var parsed = QueryHelpers.ParseQuery(Request.QueryString.Value);
            var code = parsed["code"].SingleOrDefault();
            var codeVerifier = IndexModel.CodeVerifier;

            var client = new HttpClient();
            var redirectUri = $"{ClientUrl}/gwcallback";
            var response = await client.RequestAuthorizationCodeTokenAsync(new AuthorizationCodeTokenRequest
            {
                ClientId = "gwClient",
                CodeVerifier = codeVerifier,
                RequestUri = new Uri($"{OpeniddictUrl}/connect/token"),
                RedirectUri = redirectUri,
                ClientSecret = "901564A5-E7FE-42CB-B10D-61EF6A8F3654",
                Code = code
            });

            if (response.IsError)
            {
                ResponseText = $"{response.Error}, {response.ErrorDescription}";
            }
            else
            {
                ResponseText =  response.AccessToken;
            }

            return Page(); 
        }
    }
}

PoC.OpenIddict.Client/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Cryptography;
using System.Text;

namespace PoC.OpnIddict.Client.Pages
{
    public class IndexModel : PageModel
    {
        public static string? CodeVerifier { get; private set; }
        public string ClientUrl { get; set; } = "https://localhost:7216";
        public string OpeniddictUrl { get; set; } = "https://localhost:7063";
        public static string Client { get; set; } = "gwClient";

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }

        public async Task<ActionResult> OnPostGetAsync()
        {
            return await RunAuthorizeRequestAsync(true);
        }

        public async Task<ActionResult> OnPostPostAsync()
        {
            return await RunAuthorizeRequestAsync(false);
        }

        private async Task<ActionResult> RunAuthorizeRequestAsync(bool bGet)
        {
            CodeVerifier = Guid.NewGuid().ToString();
            string codeChallenge;
            using (var sha256 = SHA256.Create())
            {
                var challengeBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(CodeVerifier));
                codeChallenge = Base64UrlEncode(challengeBytes);
            }

            var callbackUrl = $"{ClientUrl}/gwcallback";

            if (bGet)
            {
                //GET request; for test purposes
                var queryBuilder = new QueryBuilder
                {
                    { "client_id", Client },
                    { "redirect_uri", callbackUrl },
                    { "response_type", "code" },
                    { "state", Guid.NewGuid().ToString("D") },
                    { "nonce", Guid.NewGuid().ToString("D") },
                    { "code_challenge", codeChallenge },
                    { "code_challenge_method", "S256" },
                    { "myParam", "123" },
                };

                var redirectUrl = new UriBuilder(OpeniddictUrl) { Path = "/connect/authorize", Query = queryBuilder.ToString() };
                return Redirect(redirectUrl.Uri.ToString());
            }
            else
            {
                // POST Request
                var values = new Dictionary<string, string>
                {
                    { "client_id", Client },
                    { "redirect_uri", callbackUrl },
                    { "response_type", "code" },
                    { "state", Guid.NewGuid().ToString("D") },
                    { "nonce", Guid.NewGuid().ToString("D") },
                    { "code_challenge", codeChallenge },
                    { "code_challenge_method", "S256" },
                    { "myParam", "123" },
                };

                var content = new FormUrlEncodedContent(values);

                using HttpClientHandler httpClientHandler = new();
                httpClientHandler.AllowAutoRedirect = false;
                httpClientHandler.ServerCertificateCustomValidationCallback = (message, certificate2, arg3, arg4) => true;
                using (var client = new HttpClient(httpClientHandler))
                {
                    var response = await client.PostAsync($"{OpeniddictUrl}/connect/authorize", content);
                    if (response.StatusCode == System.Net.HttpStatusCode.OK || response.StatusCode == System.Net.HttpStatusCode.Found)
                    {
                        return Redirect(response.Headers.Location!.ToString());
                    }
                    else
                    {
                        var error = "n/a";
                        if (response.ReasonPhrase != null)
                        {
                            error = response.ReasonPhrase;
                        }
                        return BadRequest(error);
                    }
                }
            }
        }
        private string Base64UrlEncode(byte[] arg)
        {
            return Convert.ToBase64String(arg).Split('=')[0].Replace('+', '-').Replace('/', '_');
        }
    }
}

PoC.OpenIddict.Client/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PoC.OpnIddict.Client.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PoC.OpenIddict.Client/Pages/GwCallback.cshtml
@page
@model PoC.OpnIddict.Client.Pages.GwCallback
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Callback Page</title>
</head>
<body>
<label id="result">@Model.ResponseText</label>
</body>
</html>

PoC.OpenIddict.Client/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">PoC.Client</h1>
     <br></br>
    <form method="post">
        <button id="login" asp-page-handler="get">Start auhtorize flow (get)</button>
    </form>
    <br></br>
    <form method="post">
        <button id="login" asp-page-handler="post">Start auhtorize flow (post)</button>
    </form>
</div>

PoC.OpenIddict.Client/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PoC.OpnIddict.Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PoC.OpnIddict.Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PoC.OpnIddict.Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PoC.OpnIddict.Client - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>